/*****************************************************************/
/***┌─────────────────────────────────────────────────────────┐***/
/***│  DIFERENCIAS ENTRE SALDO ACTUAL Y SALDOS POR LOTES      │***/
/***└─────────────────────────────────────────────────────────┘***/
/*****************************************************************/
Declare @dData	as varchar(08)
Set @dData	= '20171130'

SELECT *  FROM 
(
SELECT 
	SB2.B2_COD 'CODIGO',
	LTRIM(RTRIM(SB1.B1_DESC)) 'DESCRIPCION',
	SB2.B2_LOCAL'DEPOSITO',
	CASE WHEN SB1.B1_RASTRO='L' THEN 'LOTE'
		WHEN SB1.B1_RASTRO='S' THEN 'SUBLOTE'
		WHEN SB1.B1_RASTRO IN ('N','') THEN 'NO TIENE'
	END AS 'TRAZABILIDAD',
	ROUND(SB2.B2_QATU,2) 'SALDO SB2', 
	ROUND(SB8.B8_SALDO,2) 'SALDO SB8',
	ROUND(SB2.B2_QATU,2)-ROUND(SB8.B8_SALDO,2) 'DIFERENCIA RESPECTO SB2',
	SB9.B9_QINI 'SALDO INICIAL',
	SD5.CANTIDAD,
	ROUND(SB9.B9_QINI,2) +  ROUND(SD5.CANTIDAD,2) 'TOTAL DESDE CIERRE',
	CASE	WHEN ROUND(SB9.B9_QINI+SD5.CANTIDAD,2) IN (ROUND(SB2.B2_QATU,2), SB2.B2_QATU) THEN 'SB8'
			WHEN ROUND(SB9.B9_QINI+SD5.CANTIDAD,2) in (ROUND(SB8.B8_SALDO,2), SB8.B8_SALDO) THEN 'SB2'
	END AS 'CORREGIR',
	SB2.R_E_C_N_O_ RECNOSB2

FROM SB2010 SB2
INNER JOIN (
			SELECT  
					B8_PRODUTO, 
					B8_LOCAL, 
					SUM(B8_SALDO) B8_SALDO 
			FROM	SB8010 
			WHERE  D_E_L_E_T_= ''
			GROUP BY B8_PRODUTO, B8_LOCAL
)AS SB8
ON	SB2.B2_COD		=	SB8.B8_PRODUTO 
AND SB2.B2_LOCAL	=	SB8.B8_LOCAL 


inner JOIN SB1010 SB1
on SB1.B1_COD=SB2.B2_COD

INNER JOIN (
select D5_PRODUTO, D5_LOCAL,
SUM(
CASE WHEN D5_ORIGLAN>'499' THEN (D5_QUANT*(-1))
	ELSE D5_QUANT
END ) AS CANTIDAD 
FROM SD5010
WHERE D_E_L_E_T_=''

AND D5_DATA>@dData


GROUP BY D5_PRODUTO,D5_LOCAL)
AS SD5
ON SD5.D5_PRODUTO=SB2.B2_COD
AND SD5.D5_LOCAL=SB2.B2_LOCAL

INNER JOIN SB9010 SB9
ON 
SB9.B9_COD=SB2.B2_COD 
AND SB9.B9_LOCAL=SB2.B2_LOCAL

WHERE	SB1.D_E_L_E_T_='' 
AND		SB2.D_E_L_E_T_=	''
AND		ROUND(SB2.B2_QATU,2) <> ROUND(SB8.B8_SALDO,2)
AND SB1.B1_RASTRO IN ('S','L')

AND B9_DATA=@dData
)AS TMP
WHERE TMP.CORREGIR='SB8'
ORDER BY TMP.CODIGO, TMP.DEPOSITO
